matrix:
  include:
    - language: go
      go:
        - "1.11.x"
      addons:
        apt:
          sources:
            - sourceline: 'ppa:masterminds/glide'
          packages:
            - libarchive-dev
            - glide
      env:
        - GO111MODULE=on
      go_import_path: github.com/UpdateHub/updatehub-ce
      install: true
      before_install:
        - glide install
      script:  go test -v ./...
    - language: node_js
      node_js:
        - "12.0"
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version "1.15.2"
        - export PATH="$HOME/.yarn/bin:$PATH"
        - cd ui
      install:
        - yarn install
      script:
        - yarn run lint --no-fix
